# 1   Machine learning basics

## 1.7   Getting started with the NumPy library

Insert all of the NumPy modules into the current namespace.

In [1]:
from numpy import *

Create a random array of size 4\*4.

In [2]:
random.rand(4,4)

array([[0.17811186, 0.33592004, 0.97636259, 0.30023615],
       [0.40979448, 0.80776068, 0.63067117, 0.70707832],
       [0.21237047, 0.09323114, 0.54765665, 0.15180187],
       [0.72512362, 0.2700893 , 0.14455915, 0.27074538]])

Convert an array to a matrix by calling the `mat()` function.

In [3]:
randMat = mat(random.rand(4,4))

In [6]:
print(randMat)

[[0.1232389  0.68312111 0.49105663 0.50101773]
 [0.17718441 0.19439263 0.95494793 0.46076548]
 [0.97872811 0.31073297 0.82294299 0.68993306]
 [0.05033477 0.65584221 0.61586485 0.15844132]]


The `.I` operator solves the inverse of a matrix.

In [7]:
randMat.I

matrix([[-1.04044969, -1.10495515,  1.31217598,  0.78953738],
        [ 0.5692109 , -1.15563385,  0.07379424,  1.239439  ],
        [-1.20450602,  1.13080027, -0.10283779,  0.96815872],
        [ 2.65632225,  0.73914424, -0.32258807, -2.83305226]])

In [8]:
invRandMat = randMat.I
randMat * invRandMat

matrix([[ 1.00000000e+00,  5.35638791e-17,  5.00078112e-18,
          1.94596999e-16],
        [ 5.05990556e-17,  1.00000000e+00, -3.42222973e-17,
         -4.18350872e-17],
        [-1.74637136e-16, -2.41478401e-16,  1.00000000e+00,
         -1.42316762e-16],
        [-1.36353116e-16, -3.70839230e-18,  1.03178099e-17,
          1.00000000e+00]])

Create an identity matrix using `eye()`.

In [9]:
print(eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
